const alimentos: string[] = [
    'Banana',
    'Maçã',
    'Laranja',
    'Morango',
    'Maionese',
    'Mostarda',
    'Molho de uva',
    'Maminha',
    'Uva',
    'Pêra',
    'Mamão',
    'Kiwi',
    'Melancia',
    'Abacaxi',
    'Carne',
    'Feijão',
    'Arroz',
    'Macarrão',
    'Peixe',
    'Frango',
    'Ovo',
    'Leite',
    'Queijo',
    'Iogurte',
    'Azeite',
    'Manteiga',
    'Açúcar',
    'Sal',
    'Café',
    'Suco',
    'Refrigerante',
    'Bolo',
    'Biscoito',
  ];

  export default alimentos;